name: CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build custom Postgres image for Testcontainers
        run: |
          docker build -t bddfun-database:latest ./database

      - name: Build and test with Maven
        run: |
          cd project
          mvn clean verify
